### PR TITLE
add xorg-libxrender

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by bgruening** [comment]
@conda-forge-admin, please rerender

**Comment by jdblischak** [comment]
If the problem in https://github.com/bgruening/docker-galaxy-stable/issues/420 is the same X11 issue that I am having in https://github.com/bioconda/bioconda-recipes/pull/7859, then after adding libXrender and libSM, the next required dependency will be libXext ([xorg-libxext](https://github.com/conda-forge/xorg-libxext-feedstock)).

**Comment by bgruening** [comment]
I would really appreciate a test, but was not able to pin one up until now.

**Comment by jdblischak** [comment]
I'll work on coming up with a suitable test.

**Comment by jdblischak** [comment]
OK. Here's a test that will confirm that the X11 dependencies (and also Pandoc) are installed and functional:

```
$R -e "x <- tempfile(fileext = '.Rmd'); file.create(x); rmarkdown::render(x)"  # [not win]
"\"%R%\" -e \"x <- tempfile(fileext = '.Rmd'); file.create(x); rmarkdown::render(x)\"" # [win]
```

It creates and empty file and then renders it. Both files are created in the R session's temporary directory, and are thus deleted the second the command ends. I confirmed in the galaxy-stable image that this fails when missing the X11 libraries and passes otherwise. I didn't actually check the Windows command, but presumably the CI should catch if there's a typo with all the quotation marks and backslashes.

Also, testing this in the galaxy-stable docker image was a pain because I had to manually install Miniconda first. Do you have a Docker image available that is galaxy-stable plus conda?

**Comment by bgruening** [comment]
@jdblischak added the test and hope it will crash now. Then I will fix it. Thanks a lot for your fixes.
The Galaxy Docker images containers since 2 years a conda installation. You can find it under `/tool_deps/_conda/`.

**Comment by jdblischak** [comment]
> You can find it under /tool_deps/_conda/.

@bgruening Thanks. Now I know for next time.

FYI Pandoc is now listed twice in the run-time dependencies, once at the beginning specifying a minimum version and then the one you added specifying a maximum. Support for Pandoc 2.* has been added in more recent versions of rmarkdown, so we can clean this up in the future.

**Pull request merged**
