### PR TITLE
Update r-rmarkdown to version 1.6

### PR DESCRIPTION
**Pull request by mdehollander**

### CODE REVIEW

**Comment by mdehollander** [comment]
Hi @bgruening and @johanneskoester,

Now the r-rmarkdown package is in conda-forge I have updated it here to version 1.6. The builds pass so it should be all right.
I did the update mainly to get a working package again. With the current one in the repo I get an error while loading the package in R, saying that icu=52 is needed, but icu=58 is installed. And in the repo's are only icu=>56. I hope a fresh build fixes this issue.

Mattias

**Comment by johanneskoester** [comment]
Thanks!

**Comment by johanneskoester** [comment]
I am unsure about this icu issue. Apparently, accidentally the pinning of r-base was updated I guess. I hope this won't happen again.

**Comment by johanneskoester** [comment]
I hope that these things are solved by the new pinning mechanism of conda-build 3.

**Comment by bgruening** [comment]
Thanks @mdehollander!

**Pull request merged**
