### PR TITLE
reflect upstream changes in dependencies versions

### PR DESCRIPTION
**Pull request by thomann**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by thomann** [comment]
@conda-forge-admin, please rerender

**Comment by thomann** [comment]
@conda-forge/r
This got missed in the update-PR (due to automerge) - it's green and should be merged for accurate dependency information (I was hit with a client by the incorrect information).

**Comment by jdblischak** [comment]
Thanks @thomann!

**Comment by thomann** [comment]
Thanks - that was quick!

(BTW my first open source PR!)

**Comment by jdblischak** [comment]
> Thanks - that was quick!

You're welcome! It won't always be that quick though; I don't want to set unrealistic expectations. It just happened to be at the top of my inbox when I went to check my email.

> (BTW my first open source PR!)

Welcome! May it be the first of many 😄

**Pull request merged**
